export const ventureMalay = {
  leroselle: {
    type: "Penjagaan mulut",
    title: "Mengubah ubat gigi menjadi rutin penjagaan mulut moden.",
    summary: "Strategi jenama, seni bina pembungkusan dan pengalaman perdagangan berfokuskan penukaran untuk menonjol dalam kategori yang sesak.",
    opportunity: "Rangkaian ini melayani orang dewasa dan kanak-kanak. Peluang komersialnya ialah menyatukan semua produk sebagai satu sistem keluarga yang mudah dikenali.",
    product: "Varian dewasa memudahkan pilihan mengikut keperluan harian, manakala varian buah-buahan menjadikan rutin kanak-kanak lebih mesra.",
    market: "Sistem ini dibentuk untuk farmasi, klinik pergigian, runcit, hospitaliti, e-dagang dan pasaran eksport.",
    direction: "Dunia kempen hitam, putih dan emas menaikkan nilai rangkaian sambil mengekalkan pemilihan produk yang jelas.",
    challenge: "Penjagaan mulut lazimnya dijual melalui tuntutan fungsi. Cabarannya ialah menjadikan rutin harian lebih bernilai tanpa menyukarkan pemahaman produk.",
    response: ["Memperkemas kedudukan kategori berdasarkan rutin harian yang yakin.", "Membina seni bina pembungkusan untuk pelbagai produk dan varian masa depan.", "Mereka perjalanan perdagangan daripada pendidikan kepada keyakinan produk."],
    system: ["Kedudukan", "Identiti", "Pembungkusan", "UX perdagangan", "Sistem pelancaran"],
    outcome: "Asas jenama dan digital yang koheren untuk memudahkan produk dikenali, diterangkan dan dikembangkan.",
  },
  mesfleur: {
    type: "Kecantikan",
    title: "Jenama lip matte yang dibina untuk rak era kamera.",
    summary: "Identiti dan sistem produk yang yakin, bergerak lancar daripada pembungkusan kepada kandungan pencipta dan perdagangan digital.",
    opportunity: "Koleksi ini perlu menarik perhatian sebagai objek premium di rak, keputusan rona di telefon dan kisah keyakinan dalam kempen.",
    product: "Setiap rona mempunyai personaliti tersendiri, manakala sistem pek hitam dan emas menyatukan keseluruhan koleksi sebagai Mesfleur.",
    market: "Sistem ini direka untuk butik kecantikan, farmasi, studio profesional, pencipta, e-dagang dan pengembangan pengedar.",
    direction: "Cahaya editorial hangat, potret intim dan jarak dekat produk menjadikan pemilihan rona satu kisah ekspresi diri.",
    challenge: "Produk perlu kekal tersendiri dalam runcit fizikal, perdagangan mudah alih dan kandungan pencipta yang pantas sambil menyokong pelbagai rona.",
    response: ["Membina bahasa visual berasaskan keyakinan warna dan tingkah laku produk.", "Mereka sistem rona dan pembungkusan modular untuk pengembangan rangkaian.", "Menghubungkan pendidikan produk, arahan pencipta dan penceritaan perdagangan."],
    system: ["Platform jenama", "Pembungkusan", "Seni bina rona", "Sistem kandungan", "Perdagangan"],
    outcome: "Satu sistem kecantikan yang konsisten daripada produk kepada kamera dan pembelian.",
  },
  "solid-coffee": {
    type: "Minuman",
    title: "Menjadikan kopi harian satu rutin yang dimiliki.",
    summary: "Kedudukan, pembungkusan dan enjin pengekalan yang mengubah produk komoditi menjadi platform gaya hidup berulang.",
    opportunity: "Dalam kategori pracampuran yang padat, kemudahan mudah ditiru. Wilayah yang lebih kukuh ialah perasaan berulang di sekeliling secawan kopi harian.",
    product: "Format sachet menggabungkan penyediaan mudah dengan persembahan yang kaya berasaskan aroma, keseimbangan dan keselesaan harian.",
    market: "Sistem komersial menyokong runcit, kafe, hospitaliti, pejabat, e-dagang, pemborong dan eksport.",
    direction: "Warna kopi, krim hangat dan isyarat peta mewujudkan dunia yang fleksibel daripada kandungan panduan hingga filem sinematik.",
    challenge: "Solid Coffee memerlukan sebab tersendiri untuk pembelian berulang, melangkaui asal kopi dan fotografi produk.",
    response: ["Membingkaikan jenama sebagai rutin harian berulang.", "Mencipta peraturan pembungkusan dan kandungan yang menyeimbangkan tenaga dengan kraf.", "Menghubungkan pengisian semula, bundle dan pengekalan dalam perjalanan pelanggan."],
    system: ["Kedudukan", "Pembungkusan", "Arah kandungan", "Perdagangan", "Pengekalan"],
    outcome: "Sistem produk gaya hidup untuk menyokong pengecaman, pembelian berulang dan pertumbuhan rangkaian.",
  },
  glups: {
    type: "Minuman kordial",
    title: "Sistem kordial yang mempunyai ruang untuk bermain dan berkembang.",
    summary: "Seni bina perisa modular, sistem kempen ekspresif dan pengalaman pelancaran digital untuk keluarga dan runcit moden.",
    opportunity: "Empat perisa roselle membentuk platform untuk resipi, acara dan penceritaan bermusim. Tugasnya ialah menyusun tenaga itu tanpa menghilangkan keunikannya.",
    product: "Roselle Pineapple, Rock Melon, Kurma Ajwa dan Tropical Fruits membentuk seni bina fleksibel untuk minuman sejuk, mocktail dan acara keluarga.",
    market: "Sistem ini bersedia untuk runcit, HORECA, hadiah, e-dagang, vending, pengedaran borong dan eksport.",
    direction: "Dunia buah yang cerah dan kandungan resipi dwibahasa mengubah botol menjadi permulaan kepada koleksi hidangan dan detik sosial.",
    challenge: "Rangkaian perisa memerlukan tenaga untuk keluarga dan struktur yang kekal jelas di rak, dalam talian dan kempen.",
    response: ["Membangunkan seni bina perisa modular dengan navigasi konsisten.", "Mencipta bahasa visual dan verbal yang ceria tetapi terkawal.", "Mereka aset pelancaran untuk runcit, sosial dan perdagangan digital."],
    system: ["Seni bina jenama", "Pembungkusan", "Sistem perisa", "Kempen", "Pelancaran digital"],
    outcome: "Platform kordial fleksibel yang boleh memperkenalkan perisa baharu tanpa kehilangan pengecaman keluarga.",
  },
  matts: {
    type: "Sos",
    title: "Kehadiran rak yang direka bermula daripada botol.",
    summary: "Keluarga pembungkusan yang berani dan bahasa jenama runcit-ke-sosial yang menjadikan perisa mudah difahami tanpa kehilangan kredibiliti kraf.",
    opportunity: "Matt’s perlu berfungsi sebagai jenama perisa harian yang boleh dipercayai dan keluarga FMCG yang boleh berkembang.",
    product: "Portfolio bergerak daripada sos tomato dan cili kepada kicap manis, pedas dan gaya Korea melalui seni bina botol dan label yang konsisten.",
    market: "Rangkaian distrukturkan untuk runcit, restoran, kafe, katering, hospitaliti, bekalan servis makanan, e-dagang dan eksport.",
    direction: "Fotografi makanan yang kaya, gerakan berasaskan selera dan blok warna kukuh menjadikan perisa segera difahami.",
    challenge: "Rangkaian perlu menyampaikan perisa dengan pantas dalam persekitaran runcit yang sibuk sambil mengekalkan kehangatan jenama sos berkualiti.",
    response: ["Membina seni bina botol dan label untuk pengecaman perisa pantas.", "Menyeimbangkan kod rak yang berani dengan kisah produk yang kukuh.", "Mengembangkan sistem ke aplikasi runcit, kempen dan sosial."],
    system: ["Pemurnian jenama", "Pembungkusan", "Seni bina rangkaian", "Aset runcit", "Kandungan"],
    outcome: "Keluarga produk yang lebih jelas untuk memudahkan pilihan perisa dan pengembangan masa depan.",
  },
  tomms: {
    type: "Suplemen kesihatan",
    title: "Keputusan kesihatan yang jelas, dipercayai dan manusiawi.",
    summary: "Jenama berasaskan kepercayaan, sistem maklumat dan perjalanan langganan yang mengubah kerumitan menjadi tindakan harian yang yakin.",
    opportunity: "Kategori kesihatan meminta pelanggan memproses banyak maklumat. Tomm’s memerlukan sistem yang lebih tenang dan bertanggungjawab.",
    product: "Anggur laut organik atau latok diterjemahkan kepada format kunyahan yang mudah didekati dengan dua varian yang jelas.",
    market: "Tawaran ini sesuai untuk farmasi, peruncit kesihatan, klinik, runcit, e-dagang, ejen, stokis, hadiah korporat dan eksport.",
    direction: "Fotografi bahan jarak dekat dan suasana semula jadi membina dunia kesihatan yang dipercayai sambil mengekalkan penggunaan yang mudah difahami.",
    challenge: "Pelanggan suplemen sering berhadapan maklumat padat dan pilihan tidak pasti. Pengalaman perlu menyokong pemahaman tanpa janji yang tidak disokong.",
    response: ["Menyusun jenama berasaskan kejelasan, rutin dan panduan bertanggungjawab.", "Mereka hierarki maklumat untuk bahan, penggunaan dan kesesuaian produk.", "Memetakan laluan mudah daripada pendidikan kepada pembelian semula."],
    system: ["Kedudukan", "Identiti", "Reka bentuk maklumat", "UX perdagangan", "Langganan"],
    outcome: "Sistem berasaskan kepercayaan yang memudahkan maklumat produk dan penggunaan harian.",
  },
} as const;

export const insightMalay = {
  "designing-companies-around-intelligence": {
    category: "Strategi usaha niaga",
    readTime: "8 min",
    title: "Mengapa generasi syarikat seterusnya akan direka berasaskan kecerdasan.",
    description: "AI menghasilkan nilai tertinggi apabila ia mengubah cara syarikat mengesan, membuat keputusan dan bertindak—bukan apabila ditambah sebagai alat terpencil.",
    sections: [
      { heading: "Antara muka bukan keseluruhan sistem", paragraphs: ["Chatbot boleh berguna, tetapi persoalan strategiknya ialah apa yang berlaku di belakangnya. Adakah niat pelanggan memperbaiki keputusan produk dan setiap interaksi mengukuhkan interaksi seterusnya?", "Kecerdasan menjadi kelebihan apabila dihubungkan kepada aliran kerja sebenar, maklumat terkawal dan hasil perniagaan yang jelas."] },
      { heading: "Mulakan dengan satu keputusan", paragraphs: ["Peluang AI terbaik bermula dengan keputusan yang berulang: apa yang perlu disyorkan, diutamakan, diautomasikan atau diberi perhatian.", "Petakan maklumat, manusia dan tindakan yang terlibat. Model hanyalah satu komponen dalam gelung operasi tersebut."] },
      { heading: "Bina lapisan pembelajaran", paragraphs: ["Sistem berguna merekodkan maklum balas—sama ada jawapan membantu, intervensi mengubah tingkah laku dan pengetahuan perlu diperbaiki.", "Lapisan pembelajaran inilah yang mengubah ciri AI menjadi infrastruktur yang boleh terus berkembang."] },
    ],
  },
  "brand-as-business-interface": {
    category: "Sistem jenama",
    readTime: "6 min",
    title: "Jenama anda bukan lapisan. Ia ialah antara muka kepada perniagaan anda.",
    description: "Sistem jenama moden menghubungkan kepercayaan syarikat, fungsi produk dan pengalaman pelanggan dalam setiap keputusan.",
    sections: [
      { heading: "Identiti tanpa operasi hanyalah persembahan", paragraphs: ["Identiti visual membina pengecaman, tetapi kepercayaan terbina apabila produk, servis dan operasi memenuhi janji yang sama.", "Kerja jenama perlu mempengaruhi reka bentuk maklumat, keutamaan produk, sokongan pelanggan dan bahasa dalaman—bukan aset kempen sahaja."] },
      { heading: "Reka peraturan, bukan hasil berasingan", paragraphs: ["Sistem jenama terbaik membantu pasukan membuat keputusan konsisten melalui peraturan hierarki, suara, gerakan, imejan dan tingkah laku produk.", "Struktur ini menghasilkan kepantasan sambil melindungi keunikan."] },
      { heading: "Ukur kefahaman", paragraphs: ["Keberkesanan jenama bukan sekadar kesedaran. Nilai sama ada orang memahami tawaran, mengenali produk dan cukup yakin untuk bertindak.", "Apabila jenama dan pengalaman direka bersama, isyarat ini menjadi jelas dan boleh diperbaiki."] },
    ],
  },
  "from-campaigns-to-compounding-growth": {
    category: "Sistem pertumbuhan",
    readTime: "5 min",
    title: "Daripada kempen kepada pertumbuhan berganda: sistem operasi pertumbuhan.",
    description: "Pertumbuhan mampan datang daripada menghubungkan pemerolehan, pengetahuan pelanggan, eksperimen dan pengekalan dalam satu gelung pembelajaran.",
    sections: [
      { heading: "Kempen tamat. Sistem mengingati.", paragraphs: ["Kempen boleh meningkatkan perhatian, tetapi nilainya hilang apabila pembelajaran kekal dalam saluran dan laporan berasingan.", "Sistem pertumbuhan membawa pembelajaran ke hadapan: mesej mana menarik pelanggan tepat, pengalaman mana menukar mereka dan tingkah laku mana meramalkan pembelian semula."] },
      { heading: "Satu isyarat, pelbagai kegunaan", paragraphs: ["Soalan pelanggan boleh memperbaiki halaman pendaratan, bahan jualan, pendidikan produk dan sokongan automatik serentak.", "Kelebihan datang daripada mereka aliran pengetahuan itu, bukan mengoptimumkan setiap saluran secara berasingan."] },
      { heading: "Cipta rentak operasi", paragraphs: ["Gunakan set kecil isyarat komersial dan tingkah laku, semak secara konsisten dan terjemahkan setiap semakan kepada eksperimen berkeutamaan.", "Rentak lebih penting daripada bilangan papan pemuka. Pertumbuhan berganda apabila organisasi boleh belajar dan bertindak tanpa kelewatan tidak perlu."] },
    ],
  },
} as const;

export const mvpMalay = {
  "ai-chatbot-platform": ["Ubah setiap perbualan menjadi tindakan yang layak.", "Perniagaan servis, perdagangan dan pasukan sokongan", "Sedia untuk pelbagai saluran dan bahasa"],
  "learning-management-system": ["Jadikan kepakaran sebuah perniagaan pembelajaran berskala.", "Akademi, jurulatih dan pembelajaran perusahaan", "Daripada kohort kepada akademi berbilang penyewa"],
  "membership-website": ["Tukar audiens kepada nilai berulang yang boleh diramal.", "Pencipta, persatuan dan komuniti premium", "Peranan, peringkat dan pustaka kandungan fleksibel"],
  "lead-generation-funnel": ["Cipta laluan terukur daripada perhatian kepada perbualan jualan.", "B2B, hartanah, pendidikan dan servis bernilai tinggi", "Sedia untuk pengembangan kempen dan pasaran"],
  "crm-dashboard": ["Berikan pasukan hasil satu pandangan yang boleh dipercayai.", "Pasukan jualan, agensi dan perniagaan pelbagai lokasi", "Peringkat, pasukan dan pelaporan tersuai"],
  "booking-system": ["Ubah kesukaran penjadualan menjadi perjalanan pelanggan yang lancar.", "Klinik, hospitaliti, perunding dan servis lapangan", "Sedia untuk pelbagai lokasi dan penyedia"],
  "customer-portal": ["Jadikan setiap interaksi pelanggan jelas dan terkawal.", "Servis profesional, kewangan dan pasukan perusahaan", "Seni bina berasaskan peranan dan API"],
  "inventory-dashboard": ["Lihat risiko stok sebelum ia menjadi kehilangan hasil.", "Runcit, pengedaran dan perniagaan produk", "Sedia untuk pelbagai gudang dan integrasi ERP"],
  "analytics-dashboard": ["Ubah data berpecah kepada keputusan yang yakin.", "Pasukan kepimpinan, pertumbuhan dan operasi", "Sumber dan unit perniagaan baharu boleh disambung dengan mudah"],
  "financial-calculator": ["Ubah pilihan kewangan kompleks menjadi permintaan berkualiti.", "Kewangan, insurans, hartanah dan jualan B2B", "Pelbagai model, mata wang dan pasaran"],
  "mobile-app-mvp": ["Sahkan tabiat teras sebelum mengembangkan produk.", "Syarikat pemula, usaha korporat dan servis pengguna", "Seni bina produksi dengan pengembangan modular"],
  "marketplace-platform": ["Hubungkan penawaran dan permintaan melalui transaksi dipercayai.", "Pasaran vertikal dan perniagaan ekosistem", "Asas pelbagai rantau dan vendor"],
  "saas-dashboard": ["Lancarkan produk perisian fokus dengan ruang untuk berkembang.", "Syarikat pemula B2B dan pasukan usaha dalaman", "Seni bina berbilang penyewa berasaskan penggunaan"],
  "ai-knowledge-base": ["Jadikan pengetahuan organisasi berguna serta-merta.", "Pasukan perusahaan, sokongan dan servis terkawal", "Jutaan dokumen dan pelbagai pasukan"],
  "community-platform": ["Cipta rasa kebersamaan yang semakin kukuh dengan setiap ahli.", "Rangkaian profesional, jenama dan organisasi ahli", "Model komuniti awam, persendirian dan berbayar"],
} as const;
