export type MvpProduct = {
  id: string;
  code: string;
  name: string;
  category: "AI" | "Platforms" | "Operations" | "Commerce" | "Growth";
  promise: string;
  buildTime: string;
  idealFor: string;
  features: string[];
  scalability: string;
  stack: string[];
  metric: string;
  metricLabel: string;
};

export const mvpProducts: MvpProduct[] = [
  {
    id: "ai-chatbot-platform",
    code: "AI/01",
    name: "AI Chatbot Platform",
    category: "AI",
    promise: "Turn every conversation into qualified action.",
    buildTime: "4–6 weeks",
    idealFor: "Service businesses, commerce and support teams",
    features: ["Brand-trained chat", "Lead qualification", "Human handoff", "CRM sync"],
    scalability: "Multi-channel and multilingual ready",
    stack: ["Next.js", "OpenAI", "Postgres", "Vercel"],
    metric: "24/7",
    metricLabel: "response coverage",
  },
  {
    id: "learning-management-system",
    code: "PL/02",
    name: "Learning Management System",
    category: "Platforms",
    promise: "Productise expertise into a scalable learning business.",
    buildTime: "8–12 weeks",
    idealFor: "Academies, trainers and enterprise learning",
    features: ["Course delivery", "Learner progress", "Assessments", "Certificates"],
    scalability: "From cohort launch to multi-tenant academy",
    stack: ["Next.js", "Postgres", "Mux", "Stripe"],
    metric: "∞",
    metricLabel: "learner pathways",
  },
  {
    id: "membership-website",
    code: "PL/03",
    name: "Membership Website",
    category: "Platforms",
    promise: "Convert an audience into predictable recurring value.",
    buildTime: "5–8 weeks",
    idealFor: "Creators, associations and premium communities",
    features: ["Tiered access", "Member content", "Billing", "Engagement analytics"],
    scalability: "Flexible roles, tiers and content libraries",
    stack: ["Next.js", "Stripe", "Supabase", "Resend"],
    metric: "MRR",
    metricLabel: "revenue ready",
  },
  {
    id: "lead-generation-funnel",
    code: "GR/04",
    name: "Lead Generation Funnel",
    category: "Growth",
    promise: "Create a measurable path from attention to sales conversation.",
    buildTime: "3–5 weeks",
    idealFor: "B2B, property, education and high-value services",
    features: ["Offer pages", "Lead scoring", "Nurture sequences", "Attribution"],
    scalability: "Campaign and market expansion ready",
    stack: ["Next.js", "HubSpot", "Resend", "Analytics"],
    metric: "+32%",
    metricLabel: "modelled conversion",
  },
  {
    id: "crm-dashboard",
    code: "OP/05",
    name: "CRM Dashboard",
    category: "Operations",
    promise: "Give revenue teams one reliable view of every opportunity.",
    buildTime: "6–9 weeks",
    idealFor: "Sales teams, agencies and multi-location businesses",
    features: ["Pipeline view", "Activity tracking", "Forecasting", "Automations"],
    scalability: "Custom stages, teams and reporting",
    stack: ["Next.js", "Postgres", "HubSpot", "Recharts"],
    metric: "1×",
    metricLabel: "source of truth",
  },
  {
    id: "booking-system",
    code: "OP/06",
    name: "Booking System",
    category: "Operations",
    promise: "Turn scheduling friction into a seamless customer journey.",
    buildTime: "5–8 weeks",
    idealFor: "Clinics, hospitality, consultants and field services",
    features: ["Live availability", "Payments", "Reminders", "Resource allocation"],
    scalability: "Multi-location and multi-provider ready",
    stack: ["Next.js", "Postgres", "Stripe", "Twilio"],
    metric: "−68%",
    metricLabel: "admin friction",
  },
  {
    id: "customer-portal",
    code: "PL/07",
    name: "Customer Portal",
    category: "Platforms",
    promise: "Make every customer interaction feel clear and controlled.",
    buildTime: "7–10 weeks",
    idealFor: "Professional services, finance and enterprise teams",
    features: ["Secure access", "Project status", "Documents", "Support requests"],
    scalability: "Role-based, API-connected architecture",
    stack: ["Next.js", "Auth.js", "Postgres", "Cloudflare"],
    metric: "360°",
    metricLabel: "customer visibility",
  },
  {
    id: "inventory-dashboard",
    code: "OP/08",
    name: "Inventory Dashboard",
    category: "Operations",
    promise: "See stock risk before it becomes lost revenue.",
    buildTime: "6–10 weeks",
    idealFor: "Retail, distribution and product businesses",
    features: ["Stock visibility", "Threshold alerts", "SKU performance", "Supplier views"],
    scalability: "Multi-warehouse and ERP integration ready",
    stack: ["Next.js", "Postgres", "Python", "Cloudflare"],
    metric: "LIVE",
    metricLabel: "stock intelligence",
  },
  {
    id: "analytics-dashboard",
    code: "OP/09",
    name: "Analytics Dashboard",
    category: "Operations",
    promise: "Turn fragmented data into confident decisions.",
    buildTime: "5–8 weeks",
    idealFor: "Leadership, growth and operations teams",
    features: ["Unified KPIs", "Live reporting", "Segments", "Automated insights"],
    scalability: "New sources and business units plug in cleanly",
    stack: ["Next.js", "BigQuery", "Postgres", "Recharts"],
    metric: "1.4s",
    metricLabel: "signal refresh",
  },
  {
    id: "financial-calculator",
    code: "GR/10",
    name: "Financial Calculator",
    category: "Growth",
    promise: "Turn complex financial choices into qualified demand.",
    buildTime: "3–5 weeks",
    idealFor: "Finance, insurance, property and B2B sales",
    features: ["Scenario modelling", "Lead capture", "PDF outputs", "CRM routing"],
    scalability: "Multiple models, currencies and markets",
    stack: ["Next.js", "TypeScript", "HubSpot", "PDF"],
    metric: "3×",
    metricLabel: "engagement depth",
  },
  {
    id: "mobile-app-mvp",
    code: "PL/11",
    name: "Mobile App MVP",
    category: "Platforms",
    promise: "Validate the core habit before scaling the product.",
    buildTime: "10–14 weeks",
    idealFor: "Startups, corporate ventures and consumer services",
    features: ["Core user journey", "Push notifications", "Payments", "Product analytics"],
    scalability: "Production architecture with modular expansion",
    stack: ["React Native", "Expo", "Supabase", "PostHog"],
    metric: "0→1",
    metricLabel: "app launch",
  },
  {
    id: "marketplace-platform",
    code: "CO/12",
    name: "Marketplace Platform",
    category: "Commerce",
    promise: "Connect supply and demand around a trusted transaction.",
    buildTime: "12–16 weeks",
    idealFor: "Vertical marketplaces and ecosystem businesses",
    features: ["Listings", "Search and filters", "Transactions", "Vendor management"],
    scalability: "Multi-region, multi-vendor foundations",
    stack: ["Next.js", "Postgres", "Stripe Connect", "Algolia"],
    metric: "2-sided",
    metricLabel: "growth engine",
  },
  {
    id: "saas-dashboard",
    code: "PL/13",
    name: "SaaS Dashboard",
    category: "Platforms",
    promise: "Launch a focused software product with room to compound.",
    buildTime: "8–12 weeks",
    idealFor: "B2B startups and internal venture teams",
    features: ["Authentication", "Core workflow", "Subscriptions", "Admin controls"],
    scalability: "Multi-tenant, usage-based architecture",
    stack: ["Next.js", "Postgres", "Stripe", "Vercel"],
    metric: "SaaS",
    metricLabel: "launch ready",
  },
  {
    id: "ai-knowledge-base",
    code: "AI/14",
    name: "AI Knowledge Base",
    category: "AI",
    promise: "Make institutional knowledge instantly useful.",
    buildTime: "5–8 weeks",
    idealFor: "Enterprise teams, support and regulated services",
    features: ["Semantic search", "Source citations", "Access controls", "Content ingestion"],
    scalability: "Millions of documents and multiple teams",
    stack: ["Next.js", "OpenAI", "Vector DB", "Postgres"],
    metric: "<3s",
    metricLabel: "answer retrieval",
  },
  {
    id: "community-platform",
    code: "PL/15",
    name: "Community Platform",
    category: "Platforms",
    promise: "Create belonging that grows stronger with every member.",
    buildTime: "8–12 weeks",
    idealFor: "Professional networks, brands and member organisations",
    features: ["Member profiles", "Spaces", "Events", "Moderation"],
    scalability: "Public, private and paid community models",
    stack: ["Next.js", "Postgres", "Stream", "Stripe"],
    metric: "N×N",
    metricLabel: "network value",
  },
];

